version: "3.7"

services:
  taurus-nginx:
    build:
      context: ./
      dockerfile: ./ops/docker/prod/Dockerfile
    container_name: taurus-nginx
    ports:
      - "9001:80"
    restart: always
